version: "3.8"
services:
    app:
        image: "kooldev/php:8.1-nginx"
        ports:
            - "80:80"
            - "443:443"
        restart: "always"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
            - ./node_modules:/app/node_modules
            - /etc/letsencrypt:/etc/letsencrypt
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - kool_local
            - kool_global
    database:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: "always"
        ports:
            - "${KOOL_DATABASE_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
            MYSQL_DATABASE: "${DB_DATABASE-database}"
            MYSQL_USER: "${DB_USERNAME-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - database:/var/lib/mysql:delegated
        networks:
            - kool_local
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
    cache:
        image: redis:6-alpine
        restart: "always"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data:delegated
        networks:
            - kool_local
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    meilisearch:
        image: "getmeili/meilisearch:v0.27.0"
        restart: "always"
        ports:
            - "7720:7700"
        environment:
            - MEILI_NO_ANALYTICS=true
            - MEILI_NO_SENTRY=true
            - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
        networks:
            - kool_local
            - kool_global

networks:
    kool_local:
    kool_global:
        external: true
        name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
    database:
    cache:
