version: "3.8"
services:
    app:
        image: "kooldev/php:8.1-nginx"
        ports:
            - "${KOOL_APP_PORT:-80}:80"
            - "${KOOL_APP_PORT:-443}:443"
        restart: "always"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
            - ./node_modules:/app/node_modules
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - ./data/nginx/log:/var/log/nginx
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - kool_local
            - kool_global
    certbot:
        image: certbot/certbot:v0.36.0
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    database:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: "always"
        ports:
            - "${KOOL_DATABASE_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
            MYSQL_DATABASE: "${DB_DATABASE-database}"
            MYSQL_USER: "${DB_USERNAME-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - database:/var/lib/mysql:delegated
        networks:
            - kool_local
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
    cache:
        image: redis:6-alpine
        restart: "always"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data:delegated
        networks:
            - kool_local
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    meilisearch:
        image: "getmeili/meilisearch:v0.27.0"
        restart: "always"
        ports:
            - "7720:7700"
        environment:
            - MEILI_NO_ANALYTICS=true
            - MEILI_NO_SENTRY=true
            - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
        networks:
            - kool_local
            - kool_global

networks:
    kool_local:
    kool_global:
        external: true
        name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
    database:
    cache:
